"""Repository for DraftedClaimRecord CRUD operations."""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from patent_gap_finder.db.models import DraftedClaimRecord
from patent_gap_finder.models.drafts import ClaimSet

logger = logging.getLogger(__name__)


async def save_claim_sets(
    db: AsyncSession,
    session_id: str,
    claim_sets: list[ClaimSet],
) -> None:
    """Bulk insert all drafted claims from ClaimSet objects.

    Args:
        db: Async database session.
        session_id: UUID of the analysis session.
        claim_sets: List of ClaimSet objects to persist.
    """
    for cs in claim_sets:
        for claim in cs.claims:
            record = DraftedClaimRecord(
                id=str(uuid.uuid4()),
                session_id=session_id,
                opportunity_id=cs.opportunity_id,
                claim_number=claim.claim_number,
                claim_text=claim.claim_text,
                claim_type=claim.claim_type,
                depends_on=claim.depends_on,
                patent_claim_category=claim.patent_claim_category,
                drafting_rationale=cs.drafting_rationale,
                distinguishing_features=cs.distinguishing_features,
                ipc_codes=cs.ipc_codes,
                created_at=datetime.now(timezone.utc),
            )
            db.add(record)

    await db.flush()
    logger.info(
        "Saved %d claim sets (%d total claims) for session %s",
        len(claim_sets),
        sum(len(cs.claims) for cs in claim_sets),
        session_id,
    )


async def get_claim_sets_for_session(
    db: AsyncSession,
    session_id: str,
) -> list[dict]:
    """Retrieve drafted claims grouped by opportunity_id.

    Returns:
        List of dicts, each containing opportunity metadata and claims list.
    """
    result = await db.execute(
        select(DraftedClaimRecord)
        .where(DraftedClaimRecord.session_id == session_id)
        .order_by(
            DraftedClaimRecord.opportunity_id,
            DraftedClaimRecord.claim_number,
        )
    )
    records = list(result.scalars().all())

    # Group by opportunity_id
    grouped: dict[str, list[DraftedClaimRecord]] = {}
    for rec in records:
        opp_id = rec.opportunity_id
        if opp_id not in grouped:
            grouped[opp_id] = []
        grouped[opp_id].append(rec)

    claim_sets = []
    for opp_id, claims in grouped.items():
        first = claims[0]
        claim_sets.append({
            "opportunity_id": opp_id,
            "drafting_rationale": first.drafting_rationale or "",
            "distinguishing_features": first.distinguishing_features or [],
            "ipc_codes": first.ipc_codes or [],
            "gemini_disclaimer": (
                "DISCLAIMER: These claims were generated by an AI system and have "
                "not been reviewed by a licensed patent attorney."
            ),
            "claims": [
                {
                    "claim_number": c.claim_number,
                    "claim_text": c.claim_text,
                    "claim_type": c.claim_type,
                    "depends_on": c.depends_on,
                    "patent_claim_category": c.patent_claim_category,
                }
                for c in claims
            ],
        })

    return claim_sets


async def get_claims_for_opportunity(
    db: AsyncSession,
    opportunity_id: str,
) -> list[DraftedClaimRecord]:
    """Retrieve all drafted claims for a specific opportunity.

    Args:
        db: Async database session.
        opportunity_id: UUID of the whitespace opportunity.

    Returns:
        List of DraftedClaimRecord ORM objects.
    """
    result = await db.execute(
        select(DraftedClaimRecord)
        .where(DraftedClaimRecord.opportunity_id == opportunity_id)
        .order_by(DraftedClaimRecord.claim_number)
    )
    return list(result.scalars().all())
