"""Pydantic schemas for USPTO patent claim drafting.

Used by the claim_drafter and claim_formatter modules.
Matches the DraftedClaimRecord ORM model for persistence.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


class DraftedClaim(BaseModel):
    """A single USPTO-format patent claim."""

    claim_number: int
    claim_text: str
    claim_type: Literal["independent", "dependent"]
    depends_on: Optional[int] = None
    patent_claim_category: str  # method / system / composition


class ClaimSet(BaseModel):
    """A complete set of claims for one whitespace opportunity."""

    opportunity_id: str
    claim_text_original: str
    novelty_score: float
    recommended_scope: str  # broad / medium / narrow
    claims: list[DraftedClaim] = Field(default_factory=list)
    drafting_rationale: str = ""
    distinguishing_features: list[str] = Field(default_factory=list)
    ipc_codes: list[str] = Field(default_factory=list)
    gemini_disclaimer: str = (
        "DISCLAIMER: These claims were generated by an AI system and have not been "
        "reviewed by a licensed patent attorney. They are provided for informational "
        "purposes only and do not constitute legal advice. Before filing any patent "
        "application, consult a registered patent practitioner."
    )


class ClaimDraftReport(BaseModel):
    """Full claim drafting report for a session."""

    session_id: str
    paper_title: str
    total_opportunities: int
    claim_sets: list[ClaimSet] = Field(default_factory=list)
    drafting_summary: str = ""
    recommended_filing_order: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.utcnow())
    disclaimer: str = (
        "LEGAL DISCLAIMER: This report was generated by an AI-powered patent gap "
        "analysis tool. The patent claims, assessments, and recommendations contained "
        "herein are provided for informational and research purposes only. They do NOT "
        "constitute legal advice. No attorney-client relationship is created by use of "
        "this tool. Before filing any patent application, you must consult a registered "
        "patent attorney or agent who can conduct a proper patentability analysis, "
        "prior art search, and claim drafting review. AI-generated claims may contain "
        "errors, omissions, or fail to meet USPTO requirements. The creators of this "
        "tool accept no liability for any decisions made based on this report."
    )
