"""Gemini-powered USPTO patent claim drafter.

Uses the Gemini client to generate properly formatted independent and
dependent patent claims for each whitespace opportunity, following
USPTO claim structure rules.
"""

from __future__ import annotations

import logging
from typing import Optional

from patent_gap_finder.models.drafts import ClaimSet, DraftedClaim

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────────────
# Scope → claim count mapping
# ──────────────────────────────────────────────────────────────────────

SCOPE_DEPENDENT_COUNTS = {
    "broad": 2,
    "medium": 3,
    "narrow": 4,
}

AI_DISCLAIMER = (
    "DISCLAIMER: These claims were generated by an AI system and have not been "
    "reviewed by a licensed patent attorney. They are provided for informational "
    "purposes only and do not constitute legal advice. Before filing any patent "
    "application, consult a registered patent practitioner."
)

# ──────────────────────────────────────────────────────────────────────
# System prompt with full USPTO rules
# ──────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a US patent attorney drafting independent and dependent
patent claims for a provisional patent application.

## USPTO Claim Format Rules

### Independent Claim Structure
An independent claim has three parts:
1. PREAMBLE: introduces the invention category
   - Method claims: "A method for [doing X]"
   - System claims: "A system for [doing X]" or "An apparatus comprising"
   - Composition claims: "A composition comprising"
2. TRANSITION WORD: bridges preamble to body
   - Always use "comprising" (open-ended, allows additional elements)
3. BODY ELEMENTS: each element on its own line
   - Ended with semicolon EXCEPT the last which ends with a period
   - Use functional language: "configured to", "adapted to", "operable to"
   - Each element must be introduced before referenced (antecedent basis)
   - First mention: "a processor", subsequent: "the processor"

### Dependent Claim Structure
"The [category] of claim [N], wherein [ADDITIONAL LIMITATION]."

### Common Drafting Mistakes to AVOID
1. "improves performance" → too vague, not claimable. Use specific technical language.
2. "using AI" → not a claim element, not specific enough. Describe the actual computation.
3. "the system of the present invention" → never use "the invention" in claims.
4. Missing antecedent basis: "the processor" before "a processor" was introduced.
5. Functional claiming without structure: avoid "means for" without corresponding structure.

### Claim Scope Strategy
- If recommended_claim_scope is "broad": Draft 1 independent + 2 dependent claims.
  The independent claim covers the broadest possible version.
- If recommended_claim_scope is "medium": Draft 1 independent + 3 dependent claims.
  Add specificity in independent claim to distinguish from nearest prior art.
- If recommended_claim_scope is "narrow": Draft 1 independent + 4 dependent claims.
  Independent claim is specific enough to clearly distinguish from all cited prior art.

### Critical Rules
- The independent claim must NOT read on any of the cited prior art patents.
  Add at least one element that distinguishes from each cited patent.
- Each claim element must be on its own line ending with semicolon
  (except last which ends with period).
- Use "comprising" as the transition word for all independent claims.

You must respond with a JSON object matching the required schema exactly."""


async def draft_claim_set(
    opportunity_id: str,
    claim_text: str,
    claim_type: str,
    novelty_score: float,
    recommended_scope: str,
    gemini_assessment: str,
    ipc_codes: list[str],
    nearest_patents: list[dict],
) -> ClaimSet:
    """Draft a complete set of USPTO-format claims for one opportunity.

    Args:
        opportunity_id: UUID of the whitespace opportunity.
        claim_text: The paper claim that inspired this set.
        claim_type: method / system / composition.
        novelty_score: 0.0–1.0 novelty score.
        recommended_scope: broad / medium / narrow.
        gemini_assessment: Gemini's novelty assessment text.
        ipc_codes: IPC classification codes.
        nearest_patents: List of {title, abstract, patent_id} dicts.

    Returns:
        A populated ClaimSet with drafted claims.
    """
    from patent_gap_finder.ai.gemini_client import get_gemini_client

    client = get_gemini_client()

    # Determine dependent claim count
    dep_count = SCOPE_DEPENDENT_COUNTS.get(recommended_scope, 3)
    total_claims = 1 + dep_count

    # Build nearest patent context (first 300 chars of abstract)
    patents_context = ""
    for i, p in enumerate(nearest_patents[:3], 1):
        title = p.get("title", "Unknown")
        abstract = p.get("abstract", "")[:300]
        patents_context += f"\n{i}. \"{title}\"\n   Abstract: {abstract}\n"

    user_prompt = f"""Draft {total_claims} USPTO patent claims ({recommended_scope} scope) for this research contribution.

## Research Claim ({claim_type}):
"{claim_text}"

## Analysis Context:
- Novelty Score: {novelty_score:.2f}
- Recommended Claim Scope: {recommended_scope}
- IPC Classification: {', '.join(ipc_codes) if ipc_codes else 'Not classified'}

## Gemini Novelty Assessment:
{gemini_assessment}

## Nearest Prior Art Patents (claims MUST distinguish from these):
{patents_context}

## Required JSON Response Format:
{{
  "claims": [
    {{
      "claim_number": 1,
      "claim_text": "Full formatted claim text with proper structure",
      "claim_type": "independent",
      "depends_on": null,
      "patent_claim_category": "{claim_type}"
    }},
    {{
      "claim_number": 2,
      "claim_text": "The {claim_type} of claim 1, wherein ...",
      "claim_type": "dependent",
      "depends_on": 1,
      "patent_claim_category": "{claim_type}"
    }}
  ],
  "drafting_rationale": "2-3 sentences explaining scope decisions",
  "distinguishing_features": ["feature 1 not in prior art", "feature 2"]
}}

Draft exactly 1 independent claim (claim 1) and {dep_count} dependent claims.
Each dependent claim should narrow the independent claim with additional specific limitations."""

    from pydantic import BaseModel, Field
    from typing import Optional as Opt

    class ClaimResponse(BaseModel):
        claims: list[dict] = Field(default_factory=list)
        drafting_rationale: str = ""
        distinguishing_features: list[str] = Field(default_factory=list)

    response = await client.complete_json(
        system=SYSTEM_PROMPT,
        user=user_prompt,
        schema=ClaimResponse,
        max_tokens=2500,
    )

    # Parse claims into DraftedClaim objects
    drafted_claims: list[DraftedClaim] = []
    for c in response.claims:
        drafted_claims.append(DraftedClaim(
            claim_number=c.get("claim_number", len(drafted_claims) + 1),
            claim_text=c.get("claim_text", ""),
            claim_type=c.get("claim_type", "dependent"),
            depends_on=c.get("depends_on"),
            patent_claim_category=c.get("patent_claim_category", claim_type),
        ))

    return ClaimSet(
        opportunity_id=opportunity_id,
        claim_text_original=claim_text,
        novelty_score=novelty_score,
        recommended_scope=recommended_scope,
        claims=drafted_claims,
        drafting_rationale=response.drafting_rationale,
        distinguishing_features=response.distinguishing_features,
        ipc_codes=ipc_codes,
        gemini_disclaimer=AI_DISCLAIMER,
    )


async def draft_all_claim_sets(
    opportunities: list[dict],
    patent_details: dict[str, dict],
    min_novelty_score: float = 0.5,
) -> list[ClaimSet]:
    """Draft claims for all qualifying whitespace opportunities.

    Processes opportunities sequentially to respect Gemini rate limits.

    Args:
        opportunities: List of whitespace opportunity dicts from DB.
            Each dict should have: id, claim_text, claim_type, novelty_score,
            recommended_claim_scope, gemini_assessment, ipc_whitespace_codes,
            nearest_patent_ids, is_whitespace.
        patent_details: Mapping of patent_id → {title, abstract}.
        min_novelty_score: Minimum novelty score to draft claims for.

    Returns:
        List of ClaimSet objects, one per qualifying opportunity.
    """
    claim_sets: list[ClaimSet] = []

    # Filter to qualifying opportunities
    qualifying = [
        opp for opp in opportunities
        if opp.get("is_whitespace", False)
        and opp.get("novelty_score", 0.0) >= min_novelty_score
    ]

    if not qualifying:
        logger.info("No qualifying opportunities for claim drafting")
        return claim_sets

    logger.info(
        "Drafting claims for %d/%d opportunities (min_score=%.2f)",
        len(qualifying),
        len(opportunities),
        min_novelty_score,
    )

    for i, opp in enumerate(qualifying, 1):
        logger.info(
            "Drafting claim set %d/%d (novelty=%.2f, scope=%s)",
            i,
            len(qualifying),
            opp.get("novelty_score", 0.0),
            opp.get("recommended_claim_scope", "medium"),
        )

        # Build nearest patent context
        nearest_ids = opp.get("nearest_patent_ids") or []
        nearest_patents = []
        for pid in nearest_ids[:3]:
            details = patent_details.get(pid, {})
            if details:
                nearest_patents.append(details)

        try:
            claim_set = await draft_claim_set(
                opportunity_id=str(opp.get("id", "")),
                claim_text=opp.get("claim_text", ""),
                claim_type=opp.get("claim_type", "method"),
                novelty_score=opp.get("novelty_score", 0.0),
                recommended_scope=opp.get("recommended_claim_scope", "medium"),
                gemini_assessment=opp.get("gemini_assessment", ""),
                ipc_codes=opp.get("ipc_whitespace_codes") or [],
                nearest_patents=nearest_patents,
            )
            claim_sets.append(claim_set)
        except Exception as e:
            logger.error(
                "Failed to draft claims for opportunity %s: %s",
                opp.get("id"),
                e,
            )
            continue

    logger.info("Completed drafting %d claim sets", len(claim_sets))
    return claim_sets
