"""MCP tool: save_drafted_claims — persist LLM-drafted patent claims.

Accepts USPTO-format patent claims drafted by the host LLM and
saves them to the database.  Replaces the old Gemini-powered
claim drafting path.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone

from db.connection import get_db_session
from db.models import AnalysisSession
from db.repositories import drafts_repo
from models.drafts import ClaimSet, DraftedClaim

logger = logging.getLogger(__name__)

UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.I
)

AI_DISCLAIMER = (
    "DISCLAIMER: These claims were generated by an AI system and have not been "
    "reviewed by a licensed patent attorney. They are provided for informational "
    "purposes only and do not constitute legal advice. Before filing any patent "
    "application, consult a registered patent practitioner."
)


async def save_drafted_claims(
    session_id: str,
    claim_sets: list[dict],
) -> dict:
    """Save LLM-drafted USPTO patent claims to the database.

    Each claim_set dict should contain:
      - opportunity_id (str, required): UUID of the whitespace opportunity
      - claims (list[dict], required): List of claim dicts, each with:
          - claim_number (int)
          - claim_text (str): Full formatted claim text
          - claim_type (str): "independent" | "dependent"
          - depends_on (int | null): Claim number this depends on
          - patent_claim_category (str): "method" | "system" | "composition"
      - drafting_rationale (str): Explanation of scope decisions
      - distinguishing_features (list[str]): Features not in prior art
      - novelty_score (float): 0.0–1.0
      - recommended_scope (str): "broad" | "medium" | "narrow"
      - ipc_codes (list[str]): Relevant IPC codes

    Args:
        session_id: UUID of the analysis session.
        claim_sets: List of claim set dicts from the host LLM.

    Returns:
        Confirmation dict with claim count and next step.
    """
    session_id = session_id.strip()

    if not UUID_PATTERN.match(session_id):
        return {"error": "INVALID_SESSION_ID", "message": "Not a valid UUID"}

    if not claim_sets:
        return {
            "error": "NO_CLAIM_SETS",
            "message": "No claim sets provided.",
        }

    try:
        # Parse into ClaimSet objects
        parsed_sets: list[ClaimSet] = []
        for cs in claim_sets:
            claims_data = cs.get("claims", [])
            drafted_claims = []
            for c in claims_data:
                drafted_claims.append(DraftedClaim(
                    claim_number=c.get("claim_number", len(drafted_claims) + 1),
                    claim_text=c.get("claim_text", ""),
                    claim_type=c.get("claim_type", "dependent"),
                    depends_on=c.get("depends_on"),
                    patent_claim_category=c.get("patent_claim_category", "method"),
                ))

            parsed_sets.append(ClaimSet(
                opportunity_id=cs.get("opportunity_id", ""),
                claim_text_original=cs.get("claim_text_original", ""),
                novelty_score=float(cs.get("novelty_score", 0.5)),
                recommended_scope=cs.get("recommended_scope", "medium"),
                claims=drafted_claims,
                drafting_rationale=cs.get("drafting_rationale", ""),
                distinguishing_features=cs.get("distinguishing_features", []),
                ipc_codes=cs.get("ipc_codes", []),
                gemini_disclaimer=AI_DISCLAIMER,
            ))

        async with get_db_session() as db:
            # Save to DB
            await drafts_repo.save_claim_sets(db, session_id, parsed_sets)

            # Update session
            from sqlalchemy import update
            await db.execute(
                update(AnalysisSession)
                .where(AnalysisSession.id == session_id)
                .values(
                    claims_drafted=True,
                    updated_at=datetime.now(timezone.utc),
                )
            )
            await db.commit()

        total_claims = sum(len(cs.claims) for cs in parsed_sets)
        ind_claims = sum(
            1 for cs in parsed_sets
            for c in cs.claims if c.claim_type == "independent"
        )

        logger.info(
            "Saved %d claim sets (%d total claims) for session %s",
            len(parsed_sets), total_claims, session_id,
        )

        return {
            "session_id": session_id,
            "claim_sets_saved": len(parsed_sets),
            "total_claims": total_claims,
            "independent_claims": ind_claims,
            "dependent_claims": total_claims - ind_claims,
            "disclaimer": AI_DISCLAIMER,
            "next_step": f"Call export_report with session_id='{session_id}' to generate the PDF report",
        }

    except Exception as e:
        logger.exception("Failed to save drafted claims")
        return {
            "error": "INTERNAL_ERROR",
            "message": f"Failed to save drafted claims: {e}",
            "session_id": session_id,
        }
